### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by VN0** [Charlieras262/BeatPlayer#18] opened 2020-06-12 20:31 UTC
On Android 10, the application crashes constantly

**Comment by Charlieras262** [comment] 2020-06-13 02:31
Hello @VN0,

Could you please specify?

What is the context where the application crashes?
What do you do when the app fails?
What view is open when the app crashes?

**Comment by VN0** [comment] 2020-06-13 23:59
Hello, your application crashes every time you start, the program has all the permissions.  This happens only on Android 10, on older versions there is no such problem.

**Comment by VN0** [comment] 2020-06-14 00:00
Hello @Charlieras262, your application crashes every time you start, the program has all the permissions.  This happens only on Android 10, on older versions there is no such problem.

**Comment by VN0** [comment] 2020-06-14 00:06
![Screenshot_20200614-030441](https://user-images.githubusercontent.com/37180264/84581622-f0608a80-adeb-11ea-9070-bd2b48dfc8f3.jpg)
![Screenshot_20200614-030452](https://user-images.githubusercontent.com/37180264/84581623-f22a4e00-adeb-11ea-90bf-e01f3d0da3ea.jpg)

After gaining access to the memory, the program crashes

**Comment by Charlieras262** [comment] 2020-06-14 00:16
Hi, please tell me are you using the latest app version?

**Comment by VN0** [comment] 2020-06-14 00:17
@Charlieras262 Of course, the latest release

**Comment by Charlieras262** [comment] 2020-06-14 00:28
Have you ever installed the app before?
If you've done?
Did you install the new version over the old one?

**Comment by enwokoma** [comment] 2020-06-14 06:28
@VN0, try doing a clean install by uninstalling the old one and installing the latest release from https://github.com/Charlieras262/BeatPlayer/releases/tag/v1.0.0-beta3

**Comment by VN0** [comment] 2020-06-14 16:14
@enwokoma, I tried it, but it didn't work

**Comment by VN0** [comment] 2020-06-14 16:15
@Charlieras262, I originally downloaded the new version and installed it

**Comment by enwokoma** [comment] 2020-06-14 22:03
Okay. Can you generate a logcat on your device??
If you can, please do. Generate a logcat and paste here so the issue can be traced properly.
You could use [Pastebin](pastebin.com) to paste the logcat. Then share the pastebin file here so that we can have a look.

**Comment by enwokoma** [comment] 2020-06-16 10:42
@VN0 Do you have any update on this issue?? Where you able to get a logcat?

**Comment by VN0** [comment] 2020-06-18 19:25
2020-06-18 22:16:40.505 3109-11927/? E/SQLiteDatabase: Error inserting flex_time=2863000 job_id=-1 period=5727000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1592507800483 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 from {P:3109;U:10020}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1639)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1494)
        at apiz.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):78)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):196)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):20)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):190)
        at apex.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):8)
        at sfd.b(:com.google.android.gms@201817037@20.18.17 (120400-311416286):12)
        at sfd.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sld.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):0)
        at java.lang.Thread.run(Thread.java:919)2020-06-18 22:16:40.505 3109-11927/? E/SQLiteDatabase: Error inserting flex_time=2863000 job_id=-1 period=5727000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1592507800483 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 from {P:3109;U:10020}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1639)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1494)
        at apiz.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):78)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):196)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):20)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):190)
        at apex.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):8)
        at sfd.b(:com.google.android.gms@201817037@20.18.17 (120400-311416286):12)
        at sfd.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sld.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):0)
        at java.lang.Thread.run(Thread.java:919)

**Comment by VN0** [comment] 2020-06-18 19:25
2020-06-18 22:24:06.171 14574-14634/? E/Fabric: Settings request failed.
    io.fabric.sdk.android.services.network.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/108.177.14.94 (port 443) from /10.200.185.141 (port 46410) after 10000ms
        at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1359)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:104)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:88)
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:93)
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:70)
        at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:156)
        at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:128)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:100)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:46)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/108.177.14.94 (port 443) from /10.200.185.141 (port 46410) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1357)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:104) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:88) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:93) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:70) 
        at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:156) 
        at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:128) 
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:100) 
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:46) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28) 
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by enwokoma** [comment] 2020-06-18 19:34
Okay @VN0 Will have a look at this right away

**Comment by enwokoma** [comment] 2020-06-18 20:08
Hello @VN0 I have gone through the logcat. Have you tried opening the app for the first time with an internet connection?

**Comment by enwokoma** [comment] 2020-06-18 20:22
Why I am asking is because, having gone through your logcat, I can say this a device specific issue as it is not reproducable on other Android 10 and Android 11 devices

From what I can tell, 

> Your device is routing settings.crashlytics.com to localhost. This is most times, actively caused by an AdBlocker that is interfering with the connection?

**Comment by enwokoma** [comment] 2020-06-18 20:31
If you don't have an AdBlocker. Then, you can check here: https://stackoverflow.com/questions/24595237/crashlytics-connection-refused-failed-to-connect-to-failed-to-connect-to-api-c for possible solutions like [this one](https://stackoverflow.com/a/39244467) 

Here is the issue addressed by Hermal from the Crashlytics team here: https://stackoverflow.com/a/24611412

**Comment by enwokoma** [comment] 2020-06-18 20:39
So far, I can't seem to relate this as an issue directly related to BeatPlayer because, this can happen on your device with any app that uses Crashlytics

**Closed** 2020-06-20 14:34 UTC
